services:
  # Database
  Doctrine\ORM\EntityManager: ~

  # CQRS
  #App\Application\Shared\Bus\QueryBusInterface: '@App\Infrastructure\Shared\Tactician\Bus\QueryBus'
  #App\Application\Shared\Bus\SyncCommandBusInterface: '@App\Infrastructure\Shared\Tactician\Bus\SyncCommandBus'
  #App\Application\Shared\Bus\AsyncCommandBusInterface: '@App\Infrastructure\Shared\Tactician\Bus\AsyncCommandBus'

 # Repositories
   App\Admin\Domain\City\Repository\CityRepositoryInterface: '@App\Infrastructure\Shared\Doctrine\Repository\CityRepository'
   App\Admin\Domain\Province\Repository\ProvinceRepositoryInterface: '@App\Infrastructure\Shared\Doctrine\Repository\ProvinceRepository'
   App\Admin\Domain\User\Repository\UserRepositoryInterface: '@App\Infrastructure\Shared\Doctrine\Repository\UserRepository'
   App\Admin\Domain\User\Repository\AuthenticationRepositoryInterface: '@App\Infrastructure\Shared\Doctrine\Repository\AuthenticationRepository'