services:
  #_defaults:
  #    autowire: true
  #    autoconfigure: true
  #    public: false

  # Use cases
  #App\Application\:
  #  resource: '../../src/Application/*/*/Validator/{*CommandValidator.php,*QueryValidator.php}'
  #  tags:
  #    - { name: app.cqrs.command_validator }