services:
  #_defaults:
  #    autowire: true
  #    autoconfigure: true
#    public: false

  # PlantAccess
  #App\Application\PlantAccess\Shared\EventListener\PlantAccessWasCreatedListener:
  #    class: ~
  #    public: true
  #    tags:
  #        - { name: 'tactician.event_listener', event: 'App\Domain\PlantAccess\Event\PlantAccessWasCreated' }