controllers:
    resource:
        path: ../src/Admin/UI/Controller
        namespace: App\Admin\UI\Controller
    type: attribute

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin