# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

#imports:
#    - { resource: services/aliases.yaml }
#    - { resource: services/use_cases.yaml }
#    - { resource: services/translator.yaml }
#    - { resource: services/domain_events.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    admin.blog_post:
        class: App\Admin\UI\BlogPostAdmin
        tags:
            - { name: sonata.admin, model_class: App\Admin\Infrastructure\Doctrine\Entity\BlogPost, manager_type: orm, label: 'Blog post' }

    App\Admin\Application\:
        resource: '%kernel.project_dir%/src/Admin/Application/*/*/{*/*DataTransformer.php,*/*Client.php,Service/*/*Creator.php,Service/*/*Finder.php,Service/*/*Calculator.php,*/*/*Updater.php,Service/*/*Transformer.php}'

    App\Admin\Domain\:
        resource: '%kernel.project_dir%/src/Admin/Domain/*/{Service,Repository,Validator}/{*/*Creator.php,*/*Finder.php,*/*Getter.php,*/*Updater.php,*/*Calculator.php,*/*Deleter.php,*Validator.php}'

    App\Admin\Infrastructure\:
        resource: '%kernel.project_dir%/src/Admin/Infrastructure/*/{Repository,Logger}/{*Repository.php,Logger.php}'